In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

In [2]:
mush=pd.read_csv('mushroom.csv')

In [3]:
mush

p  x  s  n  t p.1  f  c n.1  k  ... s.2  w w.1 p.2 w.2  o p.3 k.1 s.3  u
0     e  x  s  y  t   a  f  c   b  k  ...   s  w   w   p   w  o   p   n   n  g
1     e  b  s  w  t   l  f  c   b  n  ...   s  w   w   p   w  o   p   n   n  m
2     p  x  y  w  t   p  f  c   n  n  ...   s  w   w   p   w  o   p   k   s  u
3     e  x  s  g  f   n  f  w   b  k  ...   s  w   w   p   w  o   e   n   a  g
4     e  x  y  y  t   a  f  c   b  n  ...   s  w   w   p   w  o   p   k   n  g
...  .. .. .. .. ..  .. .. ..  .. ..  ...  .. ..  ..  ..  .. ..  ..  ..  .. ..
8118  e  k  s  n  f   n  a  c   b  y  ...   s  o   o   p   o  o   p   b   c  l
8119  e  x  s  n  f   n  a  c   b  y  ...   s  o   o   p   n  o   p   b   v  l
8120  e  f  s  n  f   n  a  c   b  n  ...   s  o   o   p   o  o   p   b   c  l
8121  p  k  y  n  f   y  f  c   n  b  ...   k  w   w   p   w  o   e   w   v  l
8122  e  x  s  n  f   n  a  c   b  y  ...   s  o   o   p   o  o   p   o   c  l

[8123 rows x 23 columns]

In [4]:
mush=pd.read_csv('mushroom.csv',names=range(0,23),header=0)

In [5]:
mush=pd.DataFrame(data=mush)

In [6]:
mush

0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0     e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
1     e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
2     p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
3     e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g
4     e  x  y  y  t  a  f  c  b  n  ...  s  w  w  p  w  o  p  k  n  g
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
8118  e  k  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  b  c  l
8119  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  n  o  p  b  v  l
8120  e  f  s  n  f  n  a  c  b  n  ...  s  o  o  p  o  o  p  b  c  l
8121  p  k  y  n  f  y  f  c  n  b  ...  k  w  w  p  w  o  e  w  v  l
8122  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  o  c  l

[8123 rows x 23 columns]

In [7]:
mush.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8123 entries, 0 to 8122
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       8123 non-null   object
 1   1       8123 non-null   object
 2   2       8123 non-null   object
 3   3       8123 non-null   object
 4   4       8123 non-null   object
 5   5       8123 non-null   object
 6   6       8123 non-null   object
 7   7       8123 non-null   object
 8   8       8123 non-null   object
 9   9       8123 non-null   object
 10  10      8123 non-null   object
 11  11      8123 non-null   object
 12  12      8123 non-null   object
 13  13      8123 non-null   object
 14  14      8123 non-null   object
 15  15      8123 non-null   object
 16  16      8123 non-null   object
 17  17      8123 non-null   object
 18  18      8123 non-null   object
 19  19      8123 non-null   object
 20  20      8123 non-null   object
 21  21      8123 non-null   object
 22  22      8123 non-null   

In [8]:
column_labels = [
    'class', 'cap shape', 'cap surface', 'cap color', 'bruised', 'odor',
    'gill attachment', 'gill spacing', 'gill size', 'gill color', 
    'stalk shape', 'stalk root', 'stalk surface above ring',
    'stalk surface below ring', 'stalk color above ring',
    'stalk color below ring', 'veil type', 'veil color', 'ring number',
    'ring type', 'spore print color', 'population', 'habitat'
]

mush.columns = column_labels

In [9]:
mush = mush[mush['stalk root'] != '?']

In [10]:
x= mush.loc[:, mush.columns != 'class']
x.head()

cap shape cap surface cap color bruised odor gill attachment gill spacing  \
0         x           s         y       t    a               f            c   
1         b           s         w       t    l               f            c   
2         x           y         w       t    p               f            c   
3         x           s         g       f    n               f            w   
4         x           y         y       t    a               f            c   

  gill size gill color stalk shape  ... stalk surface below ring  \
0         b          k           e  ...                        s   
1         b          n           e  ...                        s   
2         n          n           e  ...                        s   
3         b          k           t  ...                        s   
4         b          n           e  ...                        s   

  stalk color above ring stalk color below ring veil type veil color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring number ring type spore print color population habitat  
0           o         p                 n          n       g  
1           o         p                 n          n       m  
2           o         p                 k          s       u  
3           o         e                 n          a       g  
4           o         p                 k          n       g  

[5 rows x 22 columns]

In [11]:
y = mush['class'].to_frame()
y.head()

class
0     e
1     e
2     p
3     e
4     e

In [12]:
y['class'].value_counts()

e    3488
p    2155
Name: class, dtype: int64

In [13]:
x_enc = pd.get_dummies(x)
x_enc.head()

cap shape_b  cap shape_c  cap shape_f  cap shape_k  cap shape_s  \
0            0            0            0            0            0   
1            1            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   cap shape_x  cap surface_f  cap surface_g  cap surface_s  cap surface_y  \
0            1              0              0              1              0   
1            0              0              0              1              0   
2            1              0              0              0              1   
3            1              0              0              1              0   
4            1              0              0              0              1   

   ...  population_n  population_s  population_v  population_y  habitat_d  \
0  ...             1             0             0             0          0   
1  ...             1             0             0             0          0   
2  ...             0             1             0             0          0   
3  ...             0             0             0             0          0   
4  ...             1             0             0             0          0   

   habitat_g  habitat_l  habitat_m  habitat_p  habitat_u  
0          1          0          0          0          0  
1          0          0          1          0          0  
2          0          0          0          0          1  
3          1          0          0          0          0  
4          1          0          0          0          0  

[5 rows x 98 columns]

In [14]:
from sklearn import preprocessing

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()
x_std = scaler.fit_transform(x_enc)

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y_enc = le.fit_transform(y.values.ravel())

In [18]:
y_enc

array([0, 0, 1, ..., 0, 1, 1])

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x_std,y_enc,test_size=0.22,stratify=y_enc,random_state=42)

In [20]:
lr=LogisticRegression()

In [21]:
lr.fit(x_train,y_train)
lr.score(x_train,y_train)
predlr=lr.predict(x_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))

1.0
[[768   0]
 [  0 474]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       768
           1       1.00      1.00      1.00       474

    accuracy                           1.00      1242
   macro avg       1.00      1.00      1.00      1242
weighted avg       1.00      1.00      1.00      1242



In [22]:
gnb=GaussianNB()

In [23]:
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

0.9967793880837359
[[764   4]
 [  0 474]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       768
           1       0.99      1.00      1.00       474

    accuracy                           1.00      1242
   macro avg       1.00      1.00      1.00      1242
weighted avg       1.00      1.00      1.00      1242



In [24]:
svc=SVC()

In [25]:
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

1.0
[[768   0]
 [  0 474]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       768
           1       1.00      1.00      1.00       474

    accuracy                           1.00      1242
   macro avg       1.00      1.00      1.00      1242
weighted avg       1.00      1.00      1.00      1242



In [26]:
dt=DecisionTreeClassifier()

In [27]:
dt.fit(x_train,y_train)
dt.score(x_train,y_train)
preddt=dt.predict(x_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))

1.0
[[768   0]
 [  0 474]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       768
           1       1.00      1.00      1.00       474

    accuracy                           1.00      1242
   macro avg       1.00      1.00      1.00      1242
weighted avg       1.00      1.00      1.00      1242



In [28]:
knn=KNeighborsClassifier()

In [29]:
knn.fit(x_train,y_train)
knn.score(x_train,y_train)
predknn=knn.predict(x_test)
print(accuracy_score(y_test,predknn))
print(confusion_matrix(y_test,predknn))
print(classification_report(y_test,predknn))

0.999194847020934
[[768   0]
 [  1 473]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       768
           1       1.00      1.00      1.00       474

    accuracy                           1.00      1242
   macro avg       1.00      1.00      1.00      1242
weighted avg       1.00      1.00      1.00      1242



In [30]:
rfc=RandomForestClassifier()

In [31]:
rfc.fit(x_train,y_train)
rfc.score(x_train,y_train)
predrfc=rfc.predict(x_test)
print(accuracy_score(y_test,predrfc))
print(confusion_matrix(y_test,predrfc))
print(classification_report(y_test,predrfc))

1.0
[[768   0]
 [  0 474]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       768
           1       1.00      1.00      1.00       474

    accuracy                           1.00      1242
   macro avg       1.00      1.00      1.00      1242
weighted avg       1.00      1.00      1.00      1242



In [32]:
# best models with 100% accuracy are RandomForestClassifier,dt=DecisionTreeClassifier,SVC,LogisticRegression

In [37]:
import joblib
joblib.dump(rfc,'mushroom_dataset.pkl')

['mushroom_dataset.pkl']

In [38]:
sk2 =joblib.load('mushroom_dataset.pkl')

In [39]:
sk2

RandomForestClassifier()

In [40]:
a=np.array(y_test)
a

array([0, 1, 0, ..., 0, 1, 0])

In [41]:
predicted=np.array(lr.predict(x_test))
happy_com=pd.DataFrame({"original":a,"predicted":predicted},index=range(len(a)))
happy_com

original  predicted
0            0          0
1            1          1
2            0          0
3            1          1
4            0          0
...        ...        ...
1237         1          1
1238         1          1
1239         0          0
1240         1          1
1241         0          0

[1242 rows x 2 columns]